spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/b2b
spring.datasource.username=postgres
spring.datasource.password=ambar2004
spring.datasource.driver-class-name=org.postgresql.Driver

jwt.secret=mySecureSecretKeyForJwtTokenGenerationAndValidation2024
jwt.expiration=86400000