FROM maven:3.9.9-eclipse-temurin-17 AS build
WORKDIR /app
COPY pom.xml .
COPY mvnw .
COPY .mvn .mvn

#Normalizar el archivo a LF sin importar cómo haya quedado guardado en el sistema del desarrollador.
RUN sed -i 's/\r$//' mvnw && chmod +x mvnw
 
RUN ./mvnw -q -e -DskipTests dependency:go-offline
COPY src src
RUN ./mvnw -q -DskipTests package
 
FROM eclipse-temurin:17-jre
WORKDIR /app
COPY --from=build /app/target/*.jar /app/app.jar
EXPOSE 8090
ENV APP_PORT=8090
CMD ["java", "-jar", "/app/app.jar"]
 