spring.application.name=control2_backend

# ================= BASE DE DATOS (POSTGRESQL) =================
# Cambia "control2_db", "postgres" y "tu_contraseña" por tus credenciales reales
spring.datasource.url=jdbc:postgresql://localhost:5432/control2_db
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

# ================= JPA / HIBERNATE & POSTGIS =================
# Dialecto específico para que Hibernate entienda los Point y Polygon de PostGIS
spring.jpa.database-platform=org.hibernate.spatial.dialect.postgis.PostgisDialect

# ddl-auto=update hace que Spring cree o actualice las tablas en base a tus @Entity automáticamente
spring.jpa.hibernate.ddl-auto=create

# Mostrar las consultas SQL en la consola (súper útil para depurar tus funciones espaciales ST_Distance, etc.)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ================= JWT (CONFIGURACIÓN DE SEGURIDAD) =================
# Clave para firmar tus tokens (debe ser larga). El tiempo de expiración está en milisegundos (ej: 86400000 = 1 día)
jwt.secret=EstaEsUnaClaveSecretaMuyLargaYSeguraParaElControl2DeArquitectura2026
jwt.expiration=86400000